apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "DART/JWT/KAKAO/NAVER/GOOGLE/URL" # 1. Secrets Manager의 보안 암호 이름
        objectType: "secretsmanager"

  # 2. 이 부분이 AWS 값을 k8s Secret 'backend-secret'으로 동기화합니다.
  secretObjects:
    - secretName: backend-secret # 생성될 쿠버네티스 Secret의 이름
      type: Opaque
      data:
        - objectName: "DART/JWT/KAKAO/NAVER/GOOGLE/URL" # 위 objectName과 동일하게
          key: "*" # 모든 키-값 쌍을 가져옵니다