apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hihi1260/backend-image:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
