apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # web_api 역할 노드에서만 실행
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - web_api
      containers:
        - name: frontend
          image: <ECR_REGISTRY>/srg/frontend:<IMAGE_TAG>  # GitHub Actions에서 교체
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
