apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # ALB가 접근할 포트
      targetPort: 3000 # Pod 컨테이너 포트
  type: ClusterIP
