# backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: infra
spec:
  replicas: 1
---
# ai
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  namespace: infra
spec:
  replicas: 1
---
# frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: infra
spec:
  replicas: 2
---
